[couchpotato]
host = "http://192.168.1.10"
apiKey = "abc123"
slackToken = "abc123"

[sonarr] # not implemented
host = "http://192.168.1.10"
apiKey = "abc123"
slackToken = "abc123"

[plex] # not implemented
host = "http://192.168.1.10"
token = "abc123"
slackToken = "abc123"

[slack]
# incomingWebhook is required to post to slack
incomingWebhook = "http://hooks.slack.com/services"
botName = "ShartBot"

[shart]
host = "localhost:4040"